### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by PeterDaveHello**
Add CDNJS cdn info

### CODE REVIEW

**Comment by kristoferjoseph** [comment]
Added in a different update.

**Comment by PeterDaveHello** [comment]
@kristoferjoseph CDNJS is not CloudFlare, PR: #206

**Comment by kristoferjoseph** [comment]
AH my bad I was reading all the issues and there was one about the other service. My apologies for getting them confused.

**Comment by kristoferjoseph** [comment]
Fixed

**Pull request closed without merging**
