### PR TITLE
SASS version *Open for review

### PR DESCRIPTION
**Pull request by kristoferjoseph**
Opening this pr for conversations.

### CODE REVIEW

**Comment by GianlucaGuarini** [comment]
I am unable to compile. It seems libsass has several problems with selectors strings interpolation like [this](https://github.com/kristoferjoseph/flexboxgrid/blob/sass/src/sass/flexboxgrid.scss#L15)

**Comment by kristoferjoseph** [comment]
Yes, this is one of the main reasons I didn't want to support SASS in the first place. The libsass vs sass and all of possible issues that can crop up from downstream dependencies being out of sync ( gulp-sass etc. ) is kind of a nightmare.

At the time of authoring this compilation worked. @GianlucaGuarini I've added a shrinkwrap file to help with this, can you try using that and let me know if that fixes your issue?

**Comment by GianlucaGuarini** [comment]
It does not solve the problem because I am compiling using just `sass` via command line including `flexboxgrid.scss` as vendor dependency

**Comment by kristoferjoseph** [comment]
That is not a supported way to compile this project. With that said, if you can figure it out a PR is welcome.

**Pull request closed without merging**
