### PR TITLE
Add XL breakpoint support

### LINKED ISSUE #232: Support for XL like in bootstrap 4
Can you please add support for col-XL and other helpers too just like bootstrap 4.

In BS 3 grid system, there is too much gap without a break point between lg on wards. Adding XL fixes that issue.

### PR DESCRIPTION
**Pull request by rdsedmundo**
### Description
Closes #232 
This PR add support for XL (from Bootstrap 4), and additionally change the all container's width accordingly to it's [specs](https://v4-alpha.getbootstrap.com/layout/grid/#grid-options).

### Check List
__instruction : terminal command__
- [x] run the build script `grunt`
- [x] open  `index.html` in a browser & resize to test visual issues

### CODE REVIEW

**Comment by hassanasad** [comment]
I hope this commit gets pulled in - I have been waiting for this XL breakpoint for months now :)

Thanks @rdsedmundo

**Comment by Falieson** [comment]
submit it to https://github.com/Falieson/flexboxgrid/pulls

**Comment by Falieson** [comment]
Read the convo going on at https://github.com/kristoferjoseph/flexboxgrid/pull/211#issuecomment-298641394

**Comment by evgenyrodionov** [comment]
Seems like `flexboxgrid` was abandoned by @kristoferjoseph, so I forked project and made [flexboxgrid2](https://github.com/evgenyrodionov/flexboxgrid2).

What is already done:
- added breakpoint `xl` for 1200px and `sm` now pointed to 576px (#232) like Bootstrap v4,
- fixed `.container` class and now it works properly and not causing horizontal scroll (#254),
- cleaned up from messy structure (#249)

flexboxgrid2 right now is alpha5, so if you can test it and fills issues (or PRs!) I'll be very grateful.

**Pull request closed without merging**
