### PR TITLE
extensive column ordering

### PR DESCRIPTION
**Pull request by kpost**
Awesome framework! The ordering possibilities felt a little limited to me. Different ordering for different viewports feels like something that would enhance responsive web design.

### CODE REVIEW

**Comment by Nirazul** [comment]
I don't think that this is within the scope of a simple grid framework.
When you really need to do that kind of reordering, I think it's best to write custom CSS for it.

Why using non-numeric prefixes? If any at all, `order-xs-1 to 12` would have been a wiser choice. Another problem is, that it's not fit for possible future features such as flexible column numbers. For example, using a sass mixin to create a 24-grid system.

**Comment by kpost** [comment]
Good point on the prefixes. Guess I got a little distracted because the ordering stuff is surrounded by other phonetic selectors. I just kinda stayed with it.

I disagree however that column ordering would be outside of the scope of this framework. One of the main purposes of a grid framework is good responsive web design. Different positioning on different devices is as important, although neglected by many developers. A CSS based solution for positioning is something I immensely missed on frameworks like Bootstrap. And now, thanks to the flexbox property it is possible. It would seem foolish not to make full use of the possibilities. 

Besides, there is already some kind of reordering with the .first- and .last- selectors.

**Comment by Nirazul** [comment]
I didn't mean that I'm against ordering, it's great to manipulate the visual ordering with css. I just think that it's a bit too much power for a css grid on the cost of its simplicity.
Also, unfortunately the reordering won't be really intuitive. `.col-xs-order-2` doesn't put the element ot second place, but at the end. So it behaves more like z-index.

In any case, the decision maker is the author :)

**Comment by kpost** [comment]
Yeah, to use it effectively, you should not only add it to the column you want to order, but to all columns in the vicinity.

**Pull request closed without merging**
