### PR TITLE
7.0

### PR DESCRIPTION
**Pull request by kristoferjoseph**
Opening this PR so people can follow along with the progress since 7.0 will be a major change.
it will:
- [ ] Add multiple source files
    - [x] CSSNext
    - [x] Sass
    - [ ] Less
    - [ ] Stylus
- [x] Move all marketing site code to `gh-pages` branch *ONLY*
- [ ] Create an examples repo
- [ ] Update flexboxgrid.com
   - [ ] Add browser support badge

### CODE REVIEW

**Comment by AleksandrZhukov** [comment]
When SCSS source files will be in master?

**Comment by kristoferjoseph** [comment]
@AleksandrZhukov Assuming you are asking when 7.0 will be released. I am not sure yet, there is a lot of work left to do. You can use the files from this branch for now. Let me know how it works for you.

**Comment by brunowego** [comment]
Hey @kristoferjoseph, why repeat `variables.scss` code inside `flexboxgrid.scss`?

**Comment by kristoferjoseph** [comment]
@brunowego There is some debate as to whether to add the variables as a separate file or not. Personally I only want one file to include for ease of use. Others have voted for many files ( 4 to be exact ) which I feel is more developer focused than I would like for my end users. If there is one file then there is less confusion in my mind.

**Comment by nybblr** [comment]
@kristoferjoseph SASS version seems broken: no classes like `.col-xs-12` or `.col-md-4` with `width` properties are generated. I ran it through both sassc and ruby Sass.

**Comment by kristoferjoseph** [comment]
@nybblr As stated previously those flavors of sass compilers are not currently supported. Only [node-sass](https://github.com/kristoferjoseph/flexboxgrid/blob/7.0/package.json#L10)

If you can get it working with sassc or ruby sass I will gladly merge it in.

**Comment by draconteus** [comment]
Is there anyone who works on this version? I would happily contribute to push it closer to release.

**Comment by joaocunha** [comment]
@kristoferjoseph hate being _that guy_, but what is the status of 7.0? I see you last merged changes in on March.

**Comment by ShadowManu** [comment]
I'll go with the same flow as @draconteus, ask the same (anyone working?), and propose the same (contribute-happy)

**Comment by kristoferjoseph** [comment]
Version 7.0 is not going to be released with SASS support. After seeing how many issues user had trying to use incompatible SASS compilers I have decided to scrap SASS support entirely. 

I will be releasing a pure CSS version of Flexbox grid for 7.0 and will make an unsupported experimental SASS branch for people to bang their heads against. I just don't have the bandwidth to support something so fragile.

**Comment by ShadowManu** [comment]
Its not to bash and I can respect others decisions but, why not going the route of developing on SASS and publishing on CSS? That's a stable route that most projects go thorugh (users then don't really care about SASS, but power users and developers do).

Also, could you elaborate on the incompatible and fragile part? Maybe there's something we can help with, or a bug that can be reported to transpiler authors for them to fix.

**Comment by kristoferjoseph** [comment]
This was a great way to see what issues I might run into trying to support multiple flavors of the grid. I found out that this is a terrible idea. Just trying to support SASS alone opened more bugs against this branch than I currently had on the entire project. There is a sass fork for people to use. I will be only supporting the build output from this project going forward. You can import the CSS and use it! Thanks!

**Pull request closed without merging**
